<h1>Agregar Categoria</h1>
<form action="addcategory" method="POST" class="row g-3 border border-bottom border-primary m-5">
    <div class="col-md-6">
        <label class="form-label">Categoria</label>
        <input name="categoriaAdd" type="text" class="form-control">
    </div>

    <div class="col-md-6">
        <button type="submit" class="btn btn-primary position-absolute end-0">Agregar</button>
    </div>
</form>