<div id="carouselExampleAutoplaying" class="carousel slide mb-5" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <p><a href="showbycategory">ENTRADAS</a></p>
    </div>
    <div class="carousel-item">
      <p><a href="showbycategory">PRINCIPALES</a></p>
    </div>
    <div class="carousel-item">
      <p><a href="showbycategory">POSTRES</a></p>
    </div>
    <div class="carousel-item">
      <p><a href="showbycategory">BEBIDAS</a></p>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<style>
    .h {
      height: 350px;
    }
</style>