<h1>Editar Categoria</h1>
<form action="updatecategory" method="POST" class="row g-3 border border-bottom border-primary m-5">
    <div class="col-md-6">
        <label class="form-label">Id a editar</label>
        <input name="id_categoriaEditar" type="text" class="form-control">
    </div>
    <div class="col-md-6">
        <label class="form-label">Categoria Nueva</label>
        <input name="categoriaEditar" type="text" class="form-control">
    </div>
    <div class="col-md-6">
    <button type="submit" class="btn btn-primary position-absolute end-0">Editar</button>
    </div>
</form>