<h1>Editar Producto</h1>
<form action="updateproduct" method="POST" class="row g-3 border border-bottom border-primary m-5">
    <div class="col-md-6">
        <label class="form-label">Id a editar</label>
        <input name="id_productoEditar" type="text" class="form-control">
    </div>    
    <div class="col-md-6">
        <label class="form-label">Producto</label>
        <input type="text" name="nombre" class="form-control">
    </div>
    <div class="col-md-6">
        <label class="form-label">Valor</label>
        <input type="decimal" name="valor" class="form-control">
    </div>
    <div class="col-md-6">
        <label class="form-label">Descripcion</label>
        <textarea class="form-control" name="descripcion" rows="3"></textarea>
    </div>
    <div class="col-md-6">
    <label class="form-label">Categoria</label>
        <select name="id_producto" >
            <?php foreach ($categories as $category) : ?>
                <option value="<?= $category->id_producto ?>">
                    <?php echo $category->nombre ?>
                </option>                               
            <?php endforeach ?>
        </select>
    </div>
    <!--<div class="col-md-6">
        <label class="form-label">Imagen</label>
        <input type="file" name="imagen" id="imageToUpload" class="form-control">
    </div>-->
    <div class="col-md-6">
        <button type="submite" class="btn btn-primary position-absolute end-0">Modificar</button>
    </div>
</form>