
<form action="" method="POST">
    <div>
        <label>Producto</label>
        <input type="text" name="nombre">
    </div>
    <div>
        <label>Valor</label>
        <input type="number" name="valor">
    </div>
    <div>
        <label>Descripcion</label>
        <textarea name="descripcion" rows="3"></textarea>
    </div>
    <div>
        <label>id</label>
        <select name="tipo" >
            <option value="1">Entrada</option>
            <option value="2">Principal</option>
            <option value="3">Postre</option>
            <option value="4">Bebida</option>
        </select>
    </div>
    <div>
        <button type="submite">agregar</button>
    </div>

</form>