<?php require './templates/header.phtml' ?>

<?php require_once './templates/addproduct.phtml' ?>
<?php require_once './templates/editproduct.phtml' ?>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Valor</th>
            <th scope="col">Tipo</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($products as $product): ?>
            <tr>
                <th scope="row"><?= $product->id_alimento ?></th>
                <td><?= $product->nombre ?></td>
                <td><?= $product->descripcion ?></td>
                <td><?= $product->valor ?></td>
                <td><?= $product->id_producto ?></td>
                <td>
                    <a href="deleteproduct/<?= $product->id_alimento ?>" type="button" class="btn  btn-outline-danger me-md-2 p-2">Eliminar</a>
                </td>   
            </tr>
        <?php endforeach ?>
    </tbody>
   

</table>

<p class="mt-3"><small>Mostrando <?=$count?> productos</small></p>

<?php require './templates/footer.phtml' ?>