<?php require './templates/header.phtml' ?>

<?php require_once './templates/addcategory.phtml' ?>
<?php require_once './templates/editcategory.phtml' ?>

<table class="table">

    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Categoria</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($categories as $category): ?>
            <tr>
                <th scope="row"><?= $category->id_producto ?></th>
                <td><?= $category->nombre ?></td>
                <td>
                    <a href="deletecategory/<?= $category->id_producto ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                </td>   
            </tr>
        <?php endforeach ?>
    </tbody>
</table>

<p class="mt-3"><small>Mostrando <?=$count?> categorias</small></p>

<?php require './templates/footer.phtml' ?>
   