<?php

$arrCategory = [];
foreach($categorys as $category){
    $arrCategory[$category->id_producto] = $category->nombre;
}?>

<ul><?php
        $controller = new ProductController();
        foreach($products as $product){?>
                <li><span><?php echo $arrCategory[$product->id_producto].': '?></span><?php echo $product->nombre ?>
                <div>
                    <div><a href="eliminar/<?php echo $product->id_alimento ?>">eliminar</a></div>
                    <div><a href="modificar/<?php echo $product->id_alimento ?>">modificar</a></div>
                </div>
                </li><?php
            }?>
        </ul>